### ISSUE TITLE
mx.utils.StringUtil not found by asdoc

### ISSUE THREAD

**Issue by Notexe** [joshtynjala/setup-apache-flex-action#1]
Hello,
I'm using your action to automate generating asdocs but for some reason it can't find `mx.utils.StringUtil` which should be in the Flex SDK.

It's producing this error:

```
Error: Definition mx.utils:StringUtil could not be found.

import mx.utils.StringUtil;
               ^
```

I'm not sure if I'm doing something wrong or not. This is how I've setup the action in my workflow:
```yaml
      - name: Setup Apache Flex SDK
        uses: joshtynjala/setup-apache-flex-action@v2
        with:
          flex-version: "4.16.1"
          air-version: "50.2.4.4"
          accept-air-license: true
```

I have the same flex and air version installed locally.

Anyways, thank you for your time and thank you for making this action.
